.TH "/Users/jiangjinliang/work/try/Spectral_EoS/code/eostool Directory Reference" 3 "Sun Feb 7 2021" "my_ns_structure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/jiangjinliang/work/try/Spectral_EoS/code/eostool Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdata\&.hpp\fP"
.br
.ti -1c
.RI "file \fBeos_init\&.hpp\fP"
.br
.ti -1c
.RI "file \fBglobal_variable_constants\&.hpp\fP"
.br
.ti -1c
.RI "file \fBintegrate_core\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnon_param_eos\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnon_param_utils\&.hpp\fP"
.br
.ti -1c
.RI "file \fBoptimize_posterior\&.hpp\fP"
.br
.ti -1c
.RI "file \fBparam_eos\&.cpp\fP"
.br
.ti -1c
.RI "file \fBparam_utils\&.hpp\fP"
.br
.ti -1c
.RI "file \fBquark_star_utils\&.hpp\fP"
.br
.in -1c
