.TH "control_params" 3 "Sun Feb 7 2021" "my_ns_structure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
control_params
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eos_init\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmin_tov_mass\fP"
.br
.ti -1c
.RI "double \fBmax_tov_mass\fP"
.br
.ti -1c
.RI "bool \fBcheck_causal\fP"
.br
.ti -1c
.RI "int \fBparam_method\fP"
.br
.ti -1c
.RI "int \fBverbose_level\fP"
.br
.ti -1c
.RI "double \fBeos_table_max_h\fP"
.br
.ti -1c
.RI "char \fBinit_interpolation_function_type\fP [3]"
.br
.ti -1c
.RI "double \fBconst_inter_step\fP"
.br
.ti -1c
.RI "double \fBdev_G\fP"
.br
.ti -1c
.RI "bool \fBconsid_const_inter_step\fP"
.br
.ti -1c
.RI "bool \fBconsid_dev_G\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file eos_init\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool control_params::check_causal"

.PP
Definition at line 11 of file eos_init\&.hpp\&.
.SS "bool control_params::consid_const_inter_step"

.PP
Definition at line 14 of file eos_init\&.hpp\&.
.SS "bool control_params::consid_dev_G"

.PP
Definition at line 14 of file eos_init\&.hpp\&.
.SS "double control_params::const_inter_step"

.PP
Definition at line 13 of file eos_init\&.hpp\&.
.SS "double control_params::dev_G"

.PP
Definition at line 13 of file eos_init\&.hpp\&.
.SS "double control_params::eos_table_max_h"

.PP
Definition at line 12 of file eos_init\&.hpp\&.
.SS "char control_params::init_interpolation_function_type[3]"

.PP
Definition at line 12 of file eos_init\&.hpp\&.
.SS "double control_params::max_tov_mass"

.PP
Definition at line 10 of file eos_init\&.hpp\&.
.SS "double control_params::min_tov_mass"

.PP
Definition at line 10 of file eos_init\&.hpp\&.
.SS "int control_params::param_method"

.PP
Definition at line 11 of file eos_init\&.hpp\&.
.SS "int control_params::verbose_level"

.PP
Definition at line 11 of file eos_init\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for my_ns_structure from the source code\&.
