.TH "/Users/jiangjinliang/work/try/Spectral_EoS/code/eostool/data.hpp" 3 "Sun Feb 7 2021" "my_ns_structure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/jiangjinliang/work/try/Spectral_EoS/code/eostool/data.hpp
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBCOEFF_TABLE\fP [1844][4]"
.br
.ti -1c
.RI "const double \fBMR_TABLE\fP [100][2]"
.br
.ti -1c
.RI "const double \fBEP_TABLE\fP [20][2]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const double COEFF_TABLE[1844][4]"

.PP
Definition at line 5 of file data\&.hpp\&.
.SS "const double EP_TABLE[20][2]"
\fBInitial value:\fP
.PP
.nf
= {{9\&.07572e+13, 3\&.00894e+32}, 
                                {1\&.1531e+14, 5\&.15876e+32}, 
                                {1\&.46506e+14, 8\&.93302e+32}, 
                                {1\&.86142e+14, 1\&.54686e+33}, 
                                {2\&.365e+14, 2\&.67858e+33}, 
                                {3\&.00483e+14, 4\&.63828e+33}, 
                                {3\&.81775e+14, 8\&.03175e+33}, 
                                {4\&.85059e+14, 1\&.3908e+34}, 
                                {6\&.16286e+14, 2\&.40833e+34}, 
                                {7\&.83015e+14, 4\&.17032e+34}, 
                                {9\&.94851e+14, 7\&.66455e+34}, 
                                {1\&.264e+15, 1\&.473e+35}, 
                                {1\&.60596e+15, 2\&.58893e+35}, 
                                {2\&.04043e+15, 4\&.35153e+35}, 
                                {2\&.59244e+15, 6\&.78942e+35}, 
                                {3\&.29379e+15, 1\&.12431e+36}, 
                                {4\&.18489e+15, 1\&.94689e+36}, 
                                {5\&.31706e+15, 3\&.37127e+36}, 
                                {6\&.75553e+15, 5\&.83777e+36}, 
                                {8\&.58316e+15, 1\&.01088e+37}}
.fi
.PP
Definition at line 1951 of file data\&.hpp\&.
.SS "const double MR_TABLE[100][2]"

.PP
Definition at line 1850 of file data\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for my_ns_structure from the source code\&.
