.TH "non_param_struct" 3 "Sun Feb 7 2021" "my_ns_structure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
non_param_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstep_i\fP"
.br
.ti -1c
.RI "double \fBfrac\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file non_param_eos\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double non_param_struct::frac"

.PP
Definition at line 16 of file non_param_eos\&.cpp\&.
.SS "int non_param_struct::step_i"

.PP
Definition at line 15 of file non_param_eos\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for my_ns_structure from the source code\&.
