.TH "/Users/jiangjinliang/work/try/Spectral_EoS/code/eostool/non_param_eos.cpp" 3 "Sun Feb 7 2021" "my_ns_structure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/jiangjinliang/work/try/Spectral_EoS/code/eostool/non_param_eos.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include 'param_utils\&.hpp'\fP
.br
\fC#include 'non_param_utils\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBnon_param_struct\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBmy_compare\fP (map< int, double >::value_type &it1, map< int, double >::value_type &it2)"
.br
.ti -1c
.RI "void * \fBcal_like\fP (void *args)"
.br
.ti -1c
.RI "void \fBcreate_data\fP (const string f_data, const string f_mr, const string f_coeff, \fBstate_type\fP e_org, \fBstate_type\fP p_org)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* cal_like (void * args)"

.PP
Definition at line 21 of file non_param_eos\&.cpp\&.
.SS "void create_data (const string f_data, const string f_mr, const string f_coeff, \fBstate_type\fP e_org, \fBstate_type\fP p_org)"

.PP
Definition at line 28 of file non_param_eos\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 64 of file non_param_eos\&.cpp\&.
.SS "bool my_compare (map< int, double >::value_type & it1, map< int, double >::value_type & it2)\fC [inline]\fP"

.PP
Definition at line 19 of file non_param_eos\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for my_ns_structure from the source code\&.
