.TH "/Users/jiangjinliang/work/try/Spectral_EoS/code/eostool/non_param_utils.hpp" 3 "Sun Feb 7 2021" "my_ns_structure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/jiangjinliang/work/try/Spectral_EoS/code/eostool/non_param_utils.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'param_utils\&.hpp'\fP
.br
\fC#include 'integrate_core\&.hpp'\fP
.br
\fC#include <boost/math/interpolators/makima\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtransform_eostable\fP (\fBstate_type\fP e, \fBstate_type\fP p)"
.br
.ti -1c
.RI "double \fBnon_param_like\fP (int step_i, double frac, bool mktb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double non_param_like (int step_i, double frac, bool mktb)"

.PP
Definition at line 32 of file non_param_utils\&.hpp\&.
.SS "void transform_eostable (\fBstate_type\fP e, \fBstate_type\fP p)"

.PP
Definition at line 11 of file non_param_utils\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for my_ns_structure from the source code\&.
