.TH "push_back_state_and_time" 3 "Mon Dec 7 2020" "my_ns_structure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
push_back_state_and_time
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <integrate_core\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpush_back_state_and_time\fP (std::vector< \fBstate_type\fP > &states, std::vector< double > &times)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBstate_type\fP &x, double t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBstate_type\fP > & \fBm_states\fP"
.br
.ti -1c
.RI "std::vector< double > & \fBm_times\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file integrate_core\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "push_back_state_and_time::push_back_state_and_time (std::vector< \fBstate_type\fP > & states, std::vector< double > & times)\fC [inline]\fP"

.PP
Definition at line 41 of file integrate_core\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void push_back_state_and_time::operator() (const \fBstate_type\fP & x, double t)\fC [inline]\fP"

.PP
Definition at line 42 of file integrate_core\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector< \fBstate_type\fP >& push_back_state_and_time::m_states"

.PP
Definition at line 39 of file integrate_core\&.hpp\&.
.SS "std::vector< double >& push_back_state_and_time::m_times"

.PP
Definition at line 40 of file integrate_core\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for my_ns_structure from the source code\&.
