.TH "quark_params" 3 "Mon Dec 7 2020" "my_ns_structure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
quark_params
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <quark_star_utils\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBa4\fP"
.br
.ti -1c
.RI "double \fBBeff\fP"
.br
.ti -1c
.RI "double \fBegap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file quark_star_utils\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double quark_params::a4"

.PP
Definition at line 20 of file quark_star_utils\&.hpp\&.
.SS "double quark_params::Beff"

.PP
Definition at line 20 of file quark_star_utils\&.hpp\&.
.SS "double quark_params::egap"

.PP
Definition at line 20 of file quark_star_utils\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for my_ns_structure from the source code\&.
