.TH "/Users/jiangjinliang/work/try/Spectral_EoS/code/eostool/test.cpp" 3 "Mon Dec 7 2020" "my_ns_structure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/jiangjinliang/work/try/Spectral_EoS/code/eostool/test.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <string>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include 'integrate_core\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstate_type\fP \fBintegrate_func_test\fP (\fBstate_type\fP x0, void func(const \fBstate_type\fP &, \fBstate_type\fP &, double), double start_t, double end_t, bool reverse)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBstate_type\fP integrate_func_test (\fBstate_type\fP x0, void  funcconst state_type &, state_type &, double, double start_t, double end_t, bool reverse)"

.PP
Definition at line 12 of file test\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 44 of file test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for my_ns_structure from the source code\&.
