eostool: EoS Class Reference
EoS Class Reference abstract
#include <eos.hpp>
Public Member Functions
EoS ()
virtual bool eos_valid ()
virtual bool update_eos (double ppar[], int len_par, int extra_par, double h_max, const char init_function_type[])
virtual double ph (double h)=0
virtual double eh (double h)=0
virtual double rhoh (double h, double p, double e)=0
virtual double gamma (double h, double p, double e)=0
virtual double cs_sq (double p, double e, double Gamma)
virtual ~EoS ()
Public Attributes
double minimum_allowed_h = 0.0316
double eos_table_max_h =2
double suggested_hc_star = minimum_allowed_h+0.1
suggested start hc to find neutron star for specific properties.
state_type params_eos
vector< pchip< state_type > > eos_table_function_h_base
vector< pchip< state_type > > eos_table_function_rho_base
vector< pchip< state_type > > eos_table_function_e_base
state_type eos_table_h
state_type eos_table_p
state_type eos_table_e
state_type eos_table_rho
Detailed Description
Definition at line 41 of file eos.hpp.
Constructor & Destructor Documentation
EoS()
EoS::EoS () inline
Definition at line 51 of file eos.hpp.
~EoS()
virtual EoS::~EoS () inline virtual
Definition at line 59 of file eos.hpp.
Member Function Documentation
cs_sq()
virtual double EoS::cs_sq (double p, double e, double Gamma) inline virtual
Definition at line 58 of file eos.hpp.
eh()
virtual double EoS::eh (double h) pure virtual
Implemented in EoS_param_mu_cs, EoS_MIT_bag, EoS_tabulated_only, and EoS_hybrid.
Referenced by cool_eos(), find_eos_properties(), initiate_core(), int_whole_star(), integrate_eos(), and mrl_integration_system().
eos_valid()
virtual bool EoS::eos_valid () inline virtual
Reimplemented in EoS_param_mu_cs.
Definition at line 52 of file eos.hpp.
gamma()
virtual double EoS::gamma (double h, double p, double e) pure virtual
Implemented in EoS_MIT_bag, EoS_tabulated_only, and EoS_hybrid.
Referenced by cal_eos(), cool_eos(), find_eos_properties(), initiate_core(), integrate_eos(), and mrl_integration_system().
ph()
virtual double EoS::ph (double h) pure virtual
Implemented in EoS_param_mu_cs, EoS_MIT_bag, EoS_tabulated_only, and EoS_hybrid.
Referenced by cool_eos(), find_eos_properties(), initiate_core(), int_whole_star(), integrate_eos(), and mrl_integration_system().
rhoh()
virtual double EoS::rhoh (double h, double p, double e) pure virtual
Implemented in EoS_param_mu_cs, EoS_MIT_bag, EoS_tabulated_only, and EoS_hybrid.
Referenced by find_eos_properties().
update_eos()
virtual bool EoS::update_eos (double ppar[], int len_par, int extra_par, double h_max, const char init_function_type[]) inline virtual
Reimplemented in EoS_param_mu_cs, EoS_ph_sp_pt_css, EoS_pw_sp_pt_css, EoS_cons_cs, EoS_adp_pw, EoS_MIT_bag, EoS_pwg_pt, EoS_spectral_hbase, EoS_piecewise_pressure, EoS_piecewise_gamma, and EoS_tabulated_only.
Definition at line 53 of file eos.hpp.
Referenced by update_high_density_eos_parameters().
Member Data Documentation
eos_table_e
state_type EoS::eos_table_e
Definition at line 50 of file eos.hpp.
eos_table_function_e_base
vector< pchip<state_type> > EoS::eos_table_function_e_base
Definition at line 49 of file eos.hpp.
Referenced by find_eos_properties(), and interp_pe_likelihood().
eos_table_function_h_base
vector< pchip<state_type> > EoS::eos_table_function_h_base
Definition at line 47 of file eos.hpp.
eos_table_function_rho_base
vector< pchip<state_type> > EoS::eos_table_function_rho_base
Definition at line 48 of file eos.hpp.
Referenced by check_mmax_pt_two_branch(), and find_eos_properties().
eos_table_h
state_type EoS::eos_table_h
Definition at line 50 of file eos.hpp.
eos_table_max_h
double EoS::eos_table_max_h =2
Definition at line 44 of file eos.hpp.
Referenced by check_mmax_gd(), and check_mmax_old().
eos_table_p
state_type EoS::eos_table_p
Definition at line 50 of file eos.hpp.
eos_table_rho
state_type EoS::eos_table_rho
Definition at line 50 of file eos.hpp.
minimum_allowed_h
double EoS::minimum_allowed_h = 0.0316
Definition at line 43 of file eos.hpp.
Referenced by find_closest_global_property(), find_closest_global_property_with_maxm_known(), and find_closest_global_property_with_maxm_known_old().
params_eos
state_type EoS::params_eos
Definition at line 46 of file eos.hpp.
Referenced by int_whole_star().
suggested_hc_star
double EoS::suggested_hc_star = minimum_allowed_h+0.1
suggested start hc to find neutron star for specific properties.
Definition at line 45 of file eos.hpp.
Referenced by cool_eos(), find_closest_global_property(), find_closest_global_property_with_maxm_known(), find_closest_global_property_with_maxm_known_old(), and get_unknowns_from_knowns().
The documentation for this class was generated from the following file:
eostool/eos.hpp