eostool: eostool/eos.hpp File Reference
eos.hpp File Reference
#include <map>
#include <cmath>
#include <string>
#include <iostream>
#include <exception>
#include <gsl/gsl_errno.h>
#include <gsl/gsl_roots.h>
#include <boost/math/interpolators/pchip.hpp>
#include <boost/numeric/odeint/stepper/controlled_runge_kutta.hpp>
#include <boost/numeric/odeint/stepper/runge_kutta_fehlberg78.hpp>
#include <boost/numeric/odeint/integrate/integrate_adaptive.hpp>
#include "global_variable_constants.hpp"
Classes
class EoS
class EoS_tablulated
class EoS_hybrid
class EoS_tabulated_only
class EoS_piecewise_gamma
class EoS_piecewise_pressure
class EoS_spectral_hbase
class EoS_pwg_pt
class EoS_MIT_bag
struct EoS_MIT_bag::quark_params
class EoS_adp_pw
class EoS_cons_cs
class EoS_pw_sp_pt_css
class EoS_ph_sp_pt_css
class EoS_param_mu_cs
Typedefs
typedef std::vector< double > state_type
typedef runge_kutta_fehlberg78< state_type > error_stepper_type
typedef controlled_runge_kutta< error_stepper_type > controlled_stepper_type
Functions
state_type cal_eborders (state_type params, state_type rho_borders)
calculate the segement point of the energy denisty in the piecewise approx (see Appendix B of 10.1103/PhysRevD.86.084003)
void cal_eos (const state_type &x, state_type &dxdt, double h)
controlled_stepper_type controlled_stepper_cal_eos (default_error_checker< double, range_algebra, default_operations >(1e-15, 1e-9, int_a_x, int_a_dxdt))
Typedef Documentation
controlled_stepper_type
typedef controlled_runge_kutta< error_stepper_type > controlled_stepper_type
Definition at line 29 of file eos.hpp.
error_stepper_type
typedef runge_kutta_fehlberg78< state_type > error_stepper_type
Definition at line 28 of file eos.hpp.
state_type
typedef std::vector< double > state_type
Definition at line 22 of file eos.hpp.
Function Documentation
cal_eborders()
state_type cal_eborders (state_type params, state_type rho_borders)
calculate the segement point of the energy denisty in the piecewise approx (see Appendix B of 10.1103/PhysRevD.86.084003)
Definition at line 178 of file eos_utils.hpp.
References ADAPT_PIECEWISE, e_0, p_0, param_method, PHYSICAL_SPEC_PHTR_CSS, PIECE_SPEC_PHTR_CSS, PIECEWISE_GAMMA, PIECEWISE_PRESSURE, rho_0, and verbose.
Referenced by EoS_piecewise_gamma::update_eos(), EoS_piecewise_pressure::update_eos(), EoS_adp_pw::update_eos(), EoS_pw_sp_pt_css::update_eos(), and EoS_ph_sp_pt_css::update_eos().
cal_eos()
void cal_eos (const state_type & x, state_type & dxdt, double h)
Definition at line 67 of file integrate_core.hpp.
References dedh(), dpdh(), EOS, and EoS::gamma().
Referenced by EoS_hybrid::cal_eos_table(), EoS_param_mu_cs::cal_eos_table_near_pqcd(), and integrate_eos().
controlled_stepper_cal_eos()
controlled_stepper_type controlled_stepper_cal_eos (default_error_checker< double, range_algebra, default_operations > 1e-15, 1e-9, int_a_x, int_a_dxdt)
Referenced by EoS_hybrid::cal_eos_table(), and EoS_param_mu_cs::cal_eos_table_near_pqcd().