eostool: eostool/eos_utils.hpp File Reference
eos_utils.hpp File Reference
#include <iostream>
#include <exception>
#include <fstream>
#include "integrate_core.hpp"
#include <boost/math/interpolators/makima.hpp>
Classes
struct control_params
Macros
#define fail_process_find_eos_prop() for (int i=0; i<6; i++) {eos_props[i] = 0.;} return eos_props;
Typedefs
typedef std::vector< double > state_type
Functions
void init_control_params (control_params pars)
initiate global control parameters
void create_low_density_eos_with_ep_table (double ee[], double pp[], const int len_eos)
bool update_high_density_eos_parameters (double ppar[], int len_par, int extra_par, double h_max, const char init_function_type[])
accept important parameters from python script
double * find_eos_properties (double known_aim, int find_type)
Python interface function for finding eos properties from h(find_type=1), e(find_type=2) or rho(find_type=3). @params find_type must equal to init_function_type-1.
void make_eos_table (double h_start, double h_end, double dh, int precision, char *f_name, const char *unit="cgs", int get_type=1)
double interp_pe_likelihood (double *e_org, double *p_org, int size_org)
bool integrate_eos (double h_start, double h_end, double dh, state_type *h_tb, state_type *p_tb, state_type *e_tb, state_type *rho_tb, state_type *gamma_tb, state_type *v_sq_tb, int get_type)
bool cool_eos (double *hc)
state_type cal_eborders (state_type params, state_type rho_borders)
calculate the segement point of the energy denisty in the piecewise approx (see Appendix B of 10.1103/PhysRevD.86.084003)
double interp_pe_likelihood_precise (double *e_org, double *p_org, int size_org, double h_start, double h_end, double dh)
Macro Definition Documentation
fail_process_find_eos_prop
#define fail_process_find_eos_prop () for (int i=0; i<6; i++) {eos_props[i] = 0.;} return eos_props;
Typedef Documentation
state_type
typedef std::vector< double > state_type
Definition at line 14 of file eos_utils.hpp.
Function Documentation
cal_eborders()
state_type cal_eborders (state_type params, state_type rho_borders)
calculate the segement point of the energy denisty in the piecewise approx (see Appendix B of 10.1103/PhysRevD.86.084003)
Definition at line 178 of file eos_utils.hpp.
References ADAPT_PIECEWISE, e_0, p_0, param_method, PHYSICAL_SPEC_PHTR_CSS, PIECE_SPEC_PHTR_CSS, PIECEWISE_GAMMA, PIECEWISE_PRESSURE, rho_0, and verbose.
Referenced by EoS_piecewise_gamma::update_eos(), EoS_piecewise_pressure::update_eos(), EoS_adp_pw::update_eos(), EoS_pw_sp_pt_css::update_eos(), and EoS_ph_sp_pt_css::update_eos().
cool_eos()
bool cool_eos (double * hc)
Definition at line 153 of file eos_utils.hpp.
References EoS::eh(), EOS, EoS::gamma(), EoS::ph(), EoS::suggested_hc_star, and verbose.
Referenced by check_mmax_gd(), check_mmax_old(), and check_mmax_pt_two_branch().
create_low_density_eos_with_ep_table()
void create_low_density_eos_with_ep_table (double ee[], double pp[], const int len_eos)
Definition at line 293 of file eos_utils.hpp.
References ADAPT_PIECEWISE, CONS_CS, EOS, MITBAG_QUARK_STAR, param_method, PARAM_MU_CS, PHYSICAL_SPEC_PHTR_CSS, PIECE_SPEC_PHTR_CSS, PIECEWISE_GAMMA, PIECEWISE_PRESSURE, PWG_PHASE_TRANS, SPECTRAL_HBASE, SPECTRAL_HBASE_CAUSAL, and TABULATED_ONLY.
find_eos_properties()
double * find_eos_properties (double known_aim, int find_type)
Python interface function for finding eos properties from h(find_type=1), e(find_type=2) or rho(find_type=3). @params find_type must equal to init_function_type-1.
Definition at line 92 of file eos_utils.hpp.
References EoS::eh(), EOS, eos_props, EoS::eos_table_function_e_base, EoS::eos_table_function_rho_base, fail_process_find_eos_prop, EoS::gamma(), EoS::ph(), and EoS::rhoh().
init_control_params()
void init_control_params (control_params parameters)
initiate global control parameters
Definition at line 277 of file eos_utils.hpp.
References control_params::cal_internal_structure, cal_internal_structure, control_params::check_causal, check_causal, control_params::consid_const_inter_step, consid_const_inter_step, control_params::const_inter_step, control_params::max_tov_mass, maxm_tov, control_params::min_tov_mass, minm_tov, control_params::param_method, param_method, sg_const_step, verbose, control_params::verbose_level, vverbose, and vvverbose.
integrate_eos()
bool integrate_eos (double h_start, double h_end, double dh, state_type * h_tb, state_type * p_tb, state_type * e_tb, state_type * rho_tb, state_type * gamma_tb, state_type * v_sq_tb, int get_type)
Definition at line 44 of file eos_utils.hpp.
References cal_eos(), controlled_stepper(), e_0, EoS::eh(), EOS, EoS::gamma(), h_0, integrate_func(), MITBAG_QUARK_STAR, p_0, param_method, EoS::ph(), rho_0, and TABULATED_ONLY.
Referenced by interp_pe_likelihood_precise(), and make_eos_table().
interp_pe_likelihood()
double interp_pe_likelihood (double * e_org, double * p_org, int size_org)
Definition at line 224 of file eos_utils.hpp.
References EOS, and EoS::eos_table_function_e_base.
interp_pe_likelihood_precise()
double interp_pe_likelihood_precise (double * e_org, double * p_org, int size_org, double h_start, double h_end, double dh)
Definition at line 239 of file eos_utils.hpp.
References integrate_eos().
make_eos_table()
void make_eos_table (double h_start, double h_end, double dh, int precision, char * f_name, const char * unit = "cgs", int get_type = 1)
Definition at line 131 of file eos_utils.hpp.
References integrate_eos(), p_trans, rho_trans, and verbose.
update_high_density_eos_parameters()
bool update_high_density_eos_parameters (double ppar[], int len_par, int len_border, double h_max, const char init_function_type[])
accept important parameters from python script
Definition at line 327 of file eos_utils.hpp.
References EOS, and EoS::update_eos().