eostool: eostool/global_ns_prop_utils.hpp File Reference
global_ns_prop_utils.hpp File Reference
#include "eos_utils.hpp"
#include <cstdlib>
Macros
#define fail_process_check_mmax(message)
#define fail_process_check_mmax_gd(message)
#define fail_process_check_mmax_pt_two_branch(message)
#define fail_process_find_global_prop() *h_closest = -1; *unknown=0; return false;
#define fail_process_find_global_prop() *h_closest = -1; *unknown=0; return false;
Functions
double * get_mrl (double hc)
Python interface function for integrating the whole structure of the star.
double * calculate_internal_structure (double h)
double * get_mr_with_specific_hsurf (double hc, double h_surf)
bool check_mmax_gd (double *hc, double *M_max, double h_start=EOS->suggested_hc_star+0.08, bool compare_ftype_is_less=true, double jump_size=0.1, bool check_ok=true)
bool check_mmax_pt_two_branch (double *h1, double *h2, double *h3, double *h_max, double *m1, double *m2, double *m3, double *m_max, double rho_tr, double drho)
Find maximum mass in the case that there are two branches of M-R (phase transition of EoS).
bool find_closest_global_property (double m_aim, double h_i, double h_max, double *h_closest, double *lambda, bool use_user_start_point)
Find a global property a with another global property b.
bool find_closest_global_property_with_maxm_known (double known_aim, double h_i, double h_max, double *h_closest, double *unknown, int get_type, bool use_user_start_point)
Find a global property a with another global property b after knowing the maximum central specific enthalpy h_max.
bool get_unknowns_from_knowns (double known1, double known2, double *unknown1, double *unknown2, double *h_max, int get_type)
In a BNS system: Find nearest known global properties, return corresponding unknown global ones.
void make_hmrl_tool_table (double minh, double maxh, double dh)
bool check_mmax_old (double *hc, double *M_max, double h_start, bool compare_ftype_is_less, double jump_size, bool check_ok)
Find non-rotating maximum supported mass of an EoS.
bool find_closest_global_property_with_maxm_known_old (double known_aim, double h_i, double h_max, double *h_closest, double *unknown, int get_type, bool use_user_start_point)
Macro Definition Documentation
fail_process_check_mmax
#define fail_process_check_mmax (message)
Value:
        *hc = -1; *M_max=0.; \
        if (verbose) { \
            cout<<message<<", with h="<<h<<", h_guard="<<h+h_guard<<", h_check_again="<<h+h_check_again; \
            cout<<", M="<<M<<", M_guard="<<M_guard<<", M_check_again="<<M_check_again<<endl;\
        } \
        return false;
fail_process_check_mmax_gd
#define fail_process_check_mmax_gd (message)
Value:
        *hc = -1; *M_max=0.; \
        if (verbose) { \
            cout<<message<<", with h="<<h<<", h_guard="<<h+h_guard; \
            cout<<", M="<<M<<", M_guard="<<M_guard<<endl;\
        } \
        return false;
fail_process_check_mmax_pt_two_branch
#define fail_process_check_mmax_pt_two_branch (message)
Value:
        *h1 = -1, *h2 = -1, *h3 = -1, *h_max = -1, *m1 = 0., *m2 = 0., *m3 = 0., *m_max=0.; \
        if (verbose) cout<<message<<endl; \
        return false;
fail_process_find_global_prop [1/2]
#define fail_process_find_global_prop () *h_closest = -1; *unknown=0; return false;
fail_process_find_global_prop [2/2]
#define fail_process_find_global_prop () *h_closest = -1; *unknown=0; return false;
Function Documentation
calculate_internal_structure()
double * calculate_internal_structure (double h)
Definition at line 64 of file global_ns_prop_utils.hpp.
References structure_function_h_base, structure_mr, and verbose.
check_mmax_gd()
bool check_mmax_gd (double * hc, double * M_max, double h_start = EOS->suggested_hc_star+0.08, bool compare_ftype_is_less = true, double jump_size = 0.1, bool check_ok = true)
Definition at line 198 of file global_ns_prop_utils.hpp.
References check_causal, cool_eos(), EOS, EoS::eos_table_max_h, fail_process_check_mmax_gd, int_whole_star(), maxm_tov, minm_tov, and verbose.
Referenced by check_mmax_pt_two_branch(), and get_unknowns_from_knowns().
check_mmax_old()
bool check_mmax_old (double * hc, double * M_max, double h_start, bool compare_ftype_is_less, double jump_size, bool check_ok)
Find non-rotating maximum supported mass of an EoS.
The challenge is the "noise" or none monotonicity property, the solution is:
A bigger guard to check again, 2. Judge whether a step before is larger. error: ~0.005 M_sun
Parameters
hc Pointer to the central enthalpy, return -1 if finding error.
M_max Pointer to the maximum mass, return 0 if finding error.
h_start Where to start finding the maximum mass.
compare_ftype_is_less Find mimimum or maximum, set to true if maximum is wanted.
jump_size Set the initial jump size of h to find the maximum mass.
check_ok Whether to set the (mtov_min, mtov_max) constraint or not.
Return values
bool whether finding process correctly worked.
Definition at line 117 of file global_ns_prop_utils.hpp.
References check_causal, cool_eos(), EOS, EoS::eos_table_max_h, fail_process_check_mmax, int_whole_star(), maxm_tov, minm_tov, and verbose.
check_mmax_pt_two_branch()
bool check_mmax_pt_two_branch (double * h1, double * h2, double * h3, double * h_max, double * m1, double * m2, double * m3, double * m_max, double rho_tr, double drho)
Find maximum mass in the case that there are two branches of M-R (phase transition of EoS).
Need the transition density and strenth to find three critical structure and output the corresponding hc and mass.
Parameters
h1 Pointer to the central enthalpy of first peak in M-R graph, return -1 if finding error.
h2 Pointer to the central enthalpy of first valley in M-R graph, return -1 if finding error.
h3 Pointer to the central enthalpy of second peak in M-R graph, return -1 if finding error.
h_max Pointer to the central enthalpy of maximum mass in M-R graph, return -1 if finding error.
m1 Pointer to the mass corresponding to h1, return 0 if finding error.
m2 Pointer to the mass corresponding to h2, return 0 if finding error.
m3 Pointer to the mass corresponding to h3, return 0 if finding error.
m_max Pointer to the mass corresponding to h_max, return 0 if finding error.
rho_tr The starting mass density of phase transition, to boost the finding process.
drho The length of mass density of phase transition, to boost the finding process.
Return values
bool whether finding process correctly worked.
Definition at line 290 of file global_ns_prop_utils.hpp.
References check_causal, check_mmax_gd(), cool_eos(), EOS, EoS::eos_table_function_rho_base, fail_process_check_mmax_pt_two_branch, int_whole_star(), maxm_tov, minm_tov, and verbose.
find_closest_global_property()
bool find_closest_global_property (double m_aim, double h_i, double h_max, double * h_closest, double * lambda, bool use_user_start_point)
Find a global property a with another global property b.
Parameters
known_aim Global_b.
h_i Initial guess.
h_closest Pointer to the closest enthalpy, return -1 if finding error.
unknown Pointer to the global_a to be found, return 0 if finding error.
get_type 1. using mass to find lambda; 2. using mass to find radius; 3. using lambda to find mass.
use_user_start_point Whether to use user specified initial guess h_i or use system default value.
Return values
bool whether finding process correctly worked.
Definition at line 356 of file global_ns_prop_utils.hpp.
References cal_lambda(), EOS, int_whole_star(), EoS::minimum_allowed_h, EoS::suggested_hc_star, and verbose.
find_closest_global_property_with_maxm_known()
bool find_closest_global_property_with_maxm_known (double known_aim, double h_i, double h_max, double * h_closest, double * unknown, int get_type, bool use_user_start_point)
Find a global property a with another global property b after knowing the maximum central specific enthalpy h_max.
Parameters
known_aim Global_b.
h_i Initial guess.
h_max Known maximum enthalpy.
h_closest Pointer to the closest enthalpy, return -1 if finding error.
unknown Pointer to the global_a to be found, return 0 if finding error.
get_type 1. using mass to find lambda; 2. using mass to find radius; 3. using lambda to find mass.
use_user_start_point Whether to use user specified initial guess h_i or use system default value.
Return values
bool whether finding process correctly worked.
Definition at line 426 of file global_ns_prop_utils.hpp.
References cal_lambda(), EOS, fail_process_find_global_prop, int_whole_star(), EoS::minimum_allowed_h, r_trans, EoS::suggested_hc_star, and verbose.
Referenced by get_unknowns_from_knowns().
find_closest_global_property_with_maxm_known_old()
bool find_closest_global_property_with_maxm_known_old (double known_aim, double h_i, double h_max, double * h_closest, double * unknown, int get_type, bool use_user_start_point)
Definition at line 483 of file global_ns_prop_utils.hpp.
References cal_lambda(), EOS, fail_process_find_global_prop, int_whole_star(), EoS::minimum_allowed_h, r_trans, EoS::suggested_hc_star, and verbose.
get_mr_with_specific_hsurf()
double * get_mr_with_specific_hsurf (double hc, double h_surf)
Definition at line 50 of file global_ns_prop_utils.hpp.
References int_whole_star(), r_trans, structure_mr, and verbose.
get_mrl()
double * get_mrl (double hc)
Python interface function for integrating the whole structure of the star.
Give h_c, get M/M_sun, R/km and L, which are stored in global variable double *mrl_result.
Attention
Use this for python control only, because double* is convenient for python, and global variable is needed,
which may cause confuse problem if used in c++ main, so please use int_whole_star instead for c++, because that do not need to return global variable.
Parameters
hc enthalpy at the center of the compact star.
Return values
double* A double array of [mass, radius, tidal-deformability].
Definition at line 35 of file global_ns_prop_utils.hpp.
References cal_lambda(), int_whole_star(), mrl_result, r_trans, and verbose.
Referenced by get_unknowns_from_knowns().
get_unknowns_from_knowns()
bool get_unknowns_from_knowns (double known1, double known2, double * unknown1, double * unknown2, double * h_max, int get_type)
In a BNS system: Find nearest known global properties, return corresponding unknown global ones.
Parameters
known1 Known global property 1 to find with.
known2 Known global property 2 to find with.
unknown1 Unknown global property 1 to be found.
unknown2 Unknown global property 2 to be found.
h_max Pointer to stare maximum enthalpy, this should be the output also, this means this function also try to find the maximum mass.
get_type 1. using mass to find lambda; 2. using mass to find radius; 3. using lambda to find mass.
Return values
bool Whether finding process correctly worked.
Definition at line 550 of file global_ns_prop_utils.hpp.
References check_mmax_gd(), EOS, find_closest_global_property_with_maxm_known(), get_mrl(), mrl_result, and EoS::suggested_hc_star.
make_hmrl_tool_table()
void make_hmrl_tool_table (double minh, double maxh, double dh)
Definition at line 77 of file global_ns_prop_utils.hpp.
References cal_lambda(), int_whole_star(), and r_trans.