eostool: eostool/integrate_core.hpp File Reference
integrate_core.hpp File Reference
#include <boost/numeric/odeint/stepper/controlled_runge_kutta.hpp>
#include <boost/numeric/odeint/stepper/runge_kutta_fehlberg78.hpp>
#include <boost/numeric/odeint/integrate/integrate_adaptive.hpp>
#include <boost/numeric/odeint/integrate/integrate_const.hpp>
#include <iomanip>
#include "eos.hpp"
Typedefs
typedef std::vector< double > state_type
typedef runge_kutta_fehlberg78< state_type > error_stepper_type
typedef controlled_runge_kutta< error_stepper_type > controlled_stepper_type
Functions
controlled_stepper_type controlled_stepper (default_error_checker< double, range_algebra, default_operations >(int_abs_err, int_rel_err, int_a_x, int_a_dxdt))
state_type integrate_func (state_type x0, void func(const state_type &, state_type &, double), double start_t, double end_t, bool reverse)
Integrated portable function to integrate ODE.
double cal_lambda (double C, double Y)
double lambda_tilde (double m1, double m2, double l1, double l2)
double dpdh (double p, double e)
double dedh (double p, double e, double Gamma)
double dmdh (double p, double e, double m, double r)
double drdh (double p, double e, double m, double r)
double dydh (double p, double e, double m, double r, double y, double Gamma)
void cal_eos (const state_type &x, state_type &dxdt, double h)
void mrl_integration_system (const state_type &x, state_type &dxdt, double h)
state_type initiate_core (double hc, double hig=h_ig)
Integrate the most central core part of the compact star to avoid singular point.
state_type int_whole_star (double hc, double h_surf=h_surface)
Integrate the whole structure of the star.
Typedef Documentation
controlled_stepper_type
typedef controlled_runge_kutta< error_stepper_type > controlled_stepper_type
Definition at line 24 of file integrate_core.hpp.
error_stepper_type
typedef runge_kutta_fehlberg78< state_type > error_stepper_type
Definition at line 23 of file integrate_core.hpp.
state_type
typedef std::vector< double > state_type
Definition at line 15 of file integrate_core.hpp.
Function Documentation
cal_eos()
void cal_eos (const state_type & x, state_type & dxdt, double h)
Definition at line 67 of file integrate_core.hpp.
References dedh(), dpdh(), EOS, and EoS::gamma().
Referenced by EoS_hybrid::cal_eos_table(), EoS_param_mu_cs::cal_eos_table_near_pqcd(), and integrate_eos().
cal_lambda()
double cal_lambda (double C, double Y) inline
Definition at line 34 of file integrate_core.hpp.
References C.
Referenced by find_closest_global_property(), find_closest_global_property_with_maxm_known(), find_closest_global_property_with_maxm_known_old(), get_mrl(), and make_hmrl_tool_table().
controlled_stepper()
controlled_stepper_type controlled_stepper (default_error_checker< double, range_algebra, default_operations > int_abs_err, int_rel_err, int_a_x, int_a_dxdt)
Referenced by integrate_eos(), and integrate_func().
dedh()
double dedh (double p, double e, double Gamma) inline
Definition at line 46 of file integrate_core.hpp.
Referenced by cal_eos().
dmdh()
double dmdh (double p, double e, double m, double r) inline
Definition at line 48 of file integrate_core.hpp.
Referenced by mrl_integration_system().
dpdh()
double dpdh (double p, double e) inline
Definition at line 44 of file integrate_core.hpp.
Referenced by cal_eos().
drdh()
double drdh (double p, double e, double m, double r) inline
Definition at line 50 of file integrate_core.hpp.
Referenced by mrl_integration_system().
dydh()
double dydh (double p, double e, double m, double r, double y, double Gamma)
Definition at line 52 of file integrate_core.hpp.
Referenced by mrl_integration_system().
initiate_core()
state_type initiate_core (double hc, double hig = h_ig)
Integrate the most central core part of the compact star to avoid singular point.
Definition at line 149 of file integrate_core.hpp.
References EoS::eh(), EOS, EoS::gamma(), EoS::ph(), verbose, and vverbose.
Referenced by int_whole_star().
int_whole_star()
state_type int_whole_star (double hc, double h_surf = h_surface)
Integrate the whole structure of the star.
Give h_c, get m, r and y.
Note
Radius r in this function should multiply half Schwarzschild radius of the sun.
Parameters
hc enthalpy at the center of the compact star.
Definition at line 178 of file integrate_core.hpp.
References EoS::eh(), EOS, h_0, h_ig, h_surface, initiate_core(), integrate_func(), MITBAG_QUARK_STAR, mrl_integration_system(), param_method, EoS::params_eos, EoS::ph(), and verbose.
Referenced by check_mmax_gd(), check_mmax_old(), check_mmax_pt_two_branch(), find_closest_global_property(), find_closest_global_property_with_maxm_known(), find_closest_global_property_with_maxm_known_old(), get_mr_with_specific_hsurf(), get_mrl(), and make_hmrl_tool_table().
integrate_func()
state_type integrate_func (state_type x0, void funcconst state_type &, state_type &, double, double start_t, double end_t, bool reverse = true)
Integrated portable function to integrate ODE.
Definition at line 97 of file integrate_core.hpp.
References cal_internal_structure, consid_const_inter_step, controlled_stepper(), r_trans, sg_const_step, sg_step, structure_function_h_base, and vverbose.
Referenced by int_whole_star(), and integrate_eos().
lambda_tilde()
double lambda_tilde (double m1, double m2, double l1, double l2) inline
Definition at line 36 of file integrate_core.hpp.
mrl_integration_system()
void mrl_integration_system (const state_type & x, state_type & dxdt, double h)
Definition at line 81 of file integrate_core.hpp.
References dmdh(), drdh(), dydh(), EoS::eh(), EOS, EoS::gamma(), and EoS::ph().
Referenced by int_whole_star().